### ISSUE TITLE
Freezing error during large mesh generation

### ISSUE THREAD

**Issue by omedeiro** [loganbvh/py-tdgl#19]
First off, thanks so much for creating this!! It is exactly the kind of simulation tool that the field needs. 

Is it possible to have a progress bar added for the mesh creation? I have been trying to set up some simulations of thin film NbN (xi = 0.005, london_lambda = .200, d = .010)  with a total_width=1 and total_length=2 [µm]. For those dimensions and a max_edge_length=xi/2, the mesh is quite large and it is unclear if the mesh will be generated or if there is some "freezing" error. Additionally, there is a scenario where the simulation seems to run (thermalization and simulation) when creating the mesh. 

I have attached two console logs of the simulation error freezing error. 

[ipython_mesh_error2.txt](https://github.com/loganbvh/py-tdgl/files/11667318/ipython_mesh_error2.txt)
[ipython_mesh_error3.txt](https://github.com/loganbvh/py-tdgl/files/11667319/ipython_mesh_error3.txt)

**Comment by loganbvh** [comment]
Hi Owen,

I've opened a Pull Request (https://github.com/loganbvh/py-tdgl/pull/20) which optimizes the process of creating the necessary data structures after mesh generation. I've also added a progress bar to the parts of the process that take the longest.

With the new code, I get the results below. I am using `max_edge_length = xi` because `max_edge_length = xi/2` results in a mesh with over a million sites. Even with `max_edge_length = xi`, the mean edge length is roughly `xi / 2`, which is probably good enough.

The other thing to watch out for when making really large meshes is the number of points in the underlying `tdgl.Polygon`. You may have to play around with the number of points in the `Polygon` using `tdgl.Polygon.resample()` and `tdgl.Polygon.buffer()` to get rid of the `Malformed Voronoi cell surrounding boundary site` warnings.

The other error I am seeing in your logs is `RuntimeWarning: divide by zero encountered in double_scalars ... current_density = (-1 / term.length) ...`. This means that one of the `tdgl.Polygon` instances you are using to define a transport terminal doesn't actually contain any boundary mesh sites.

I will merge this PR and push the changes to PyPI later today or tomorrow. In the meantime, if you'd like you can check out the branch that has the changes: https://github.com/loganbvh/py-tdgl/tree/big-mesh

Let me know if you have any other questions!

```python
import logging
logging.basicConfig(level=logging.INFO)

import tdgl
from tdgl.geometry import box

xi = 0.005
d = 0.01
london_lambda = 0.2

layer = tdgl.Layer(coherence_length=xi, london_lambda=london_lambda, thickness=d)
film = tdgl.Polygon("film", points=box(2, 1)).resample(5001).buffer(0)
device = tdgl.Device("bar", layer=layer, film=film, length_units="um")

device.make_mesh(max_edge_length=xi)
```

Output:

```
INFO:tdgl.device.device:Generating mesh...
INFO:tdgl.device.meshing:Iteration 1: 23153 points, 41291 triangles, max_edge_length: 2.2e-01 (target: 5.0e-03).
...
INFO:tdgl.device.meshing:Iteration 22: 298368 points, 591716 triangles, max_edge_length: 4.9e-03 (target: 5.0e-03).
Finding Voronoi indices: 100%|████████████████████████████████████████████| 1775148/1775148 [00:14<00:00, 122284.12it/s]
Constructing Voronoi polygons: 100%|█████████████████████████████████████████| 298368/298368 [00:17<00:00, 16874.98it/s]
INFO:tdgl.device.device:Finished generating mesh with 298368 points and 591716 triangles.
INFO:tdgl.device.device:Total mesh generation time: 79.232 seconds
```

`device.mesh_stats_dict()`:

```
{'num_sites': 298368,
 'num_elements': 591716,
 'min_edge_length': 0.0009765625,
 'max_edge_length': 0.00494772146487779,
 'mean_edge_length': 0.0028552928379728393,
 'min_area': 2.900378605089071e-07,
 'max_area': 1.2706923858807462e-05,
 'mean_area': 6.7031299058204325e-06,
 'coherence_length': 0.005,
 'length_units': 'um'}
```
