### ISSUE TITLE
Time Dependent Applied Field

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#31]
I was wondering if there could be a method to investigate time dependent external fields? 

You could potentially solve the system for 1 field, then use the final state as the seed for the next field. However, this can quickly become tedious. Is there a simpler solution available to keep it all in 1 file?

Thank you!

**Comment by Kyroba** [comment]
I read the documentation for screening:

![image](https://github.com/loganbvh/py-tdgl/assets/34236089/f76ef0dd-2d65-4605-904a-6773a0759898)

But I am not sure what values to give for alpha and beta.

**Comment by loganbvh** [comment]
The values for alpha and beta will affect the rate of convergence, but should not affect the accuracy of results very much. I would just start with the default values. To be honest, the screening calculation slows things down so much that it is not all that useful.

I will try to add time-dependent applied vector potential soon. There are a few details I need to think about

**Comment by loganbvh** [comment]
I started a branch to work on time-dependent applied vector potential: https://github.com/loganbvh/py-tdgl/commit/33989b0fd9910bf133ab582d30ca128bc45cd69d. I need to update the documentation and tests before merging the change, but you are welcome to try it on the [time-dependent-field](https://github.com/loganbvh/py-tdgl/tree/time-dependent-field) branch in the meantime. Happy to hear any feedback you have on this


## Example

The simplest way to define a time-dependent applied field is to multiply an existing `tdgl.Parameter` for a time-independent applied vector potential (e.g. `tdgl.sources.ConstantField` or `tdgl.sources.CurrentLoop` by a time-dependent scale factor, for example a linear ramp from zero up to some value.

Using the model from the quickstart notebook:

```python
from tdgl import sources

options = tdgl.SolverOptions(
    solve_time=500,
    output_file="weak-link-zero-current.h5",
    field_units = "mT",
    current_units="uA",
    dt_max=1e-2,
)

# Ramp the applied field from 0 to 1 mT between t=0 and t=200, then hold it at 1 mT.
A_applied = (
    sources.LinearRamp(tmin=0, tmax=200)
    * sources.ConstantField(1, field_units=options.field_units, length_units=device.length_units
)

zero_current_solution = tdgl.solve(
    device,
    options,
    applied_vector_potential=A_applied,
)
``` 

https://github.com/loganbvh/py-tdgl/assets/20325010/16397678-03a9-40ff-a6af-600df9dabb7f

## More details

You can also directly define a time-dependent `tdgl.Parameter`, as in `A_applied = tdgl.Parameter(some_function, time_dependent=True, **kwargs)`, where `some_function` has a signature like `some_function(x, y, z, *, t, **kwargs)` and `t` is the dimensionless time which must be a keyword only argument.

Including a time-dependent applied vector potential slows things down a bit. This is because each time the applied vector potential changes, I have to update the [link variables](https://py-tdgl.readthedocs.io/en/latest/background.html#covariant-derivatives) in the covariant gradient and Laplacian for \psi. Updating all of these elements of a sparse matrix takes some time.

**Comment by Kyroba** [comment]
Very nice! The initialization of more vortices as the field increases looks great!

**Comment by loganbvh** [comment]
I am going to close this issue because I have merged https://github.com/loganbvh/py-tdgl/pull/33, which adds support for time-dependent vector potentials
