### ISSUE TITLE
Time dependent disorder_epsilon

### ISSUE THREAD

**Issue by omedeiro** [loganbvh/py-tdgl#58]
is it possible to have an option for a time-dependent `disorder_epsilon`  callable function? In the same way `current_func(t)` is called? 

something like `disorder_epsilon(r, t)`

**Comment by loganbvh** [comment]
Hi Owen,

Yes, that's a good idea. I need to do some digging in the literature to figure out the correct definition for epsilon(r). Some references say epsilon = 1 - T/T_c and others say epsilon = T_c/T - 1, which is a bit annoying. Currently pyTDGL uses the latter definition. The two expressions are quite close in the region t=T/T_c ~ 1

<img width="412" alt="image" src="https://github.com/loganbvh/py-tdgl/assets/20325010/74f5268d-d032-4a43-9b00-9105a90f31ad">

**Comment by loganbvh** [comment]
At some point, I would like to couple epsilon to the heat diffusion equation to model Joule heating. In that case, epsilon will be inherently time-dependent.

**Comment by loganbvh** [comment]
Hi @omedeiro,

I started a PR for this feature: https://github.com/loganbvh/py-tdgl/pull/63

Here's an example where I have `epsilon(r, t) = 1` for all `r` when `t <= 200`, then for `t > 200` I set `epsilon(r, t)` to be a Gaussian function of `r`

```python
def epsilon(r, *, t, vectorized=True):
    sigma = 0.5
    rho2 = np.sum(r**2, axis=1)
    eps = np.ones(len(r), dtype=float)
    if t > 200:
        eps -= 1 * np.exp(-rho2 / (2 * sigma**2))
    return eps
```

I added this special `vectorized=True` keyword argument to indicate that the `disorder_epsilon` function is written in a vectorized fashion, i.e. it assumes that `r` is the array of all mesh sites rather than a single mesh site. If you have a non-vectorized and time-dependent `disorder_epsilon`, the `disorder_epsilon` function needs to be called `N_mesh_sites * N_solve_steps` times. Since there's significant overhead to function calls in Python, this slows things down a lot.

In the animation below, you can see vortices getting pulled into the region with suppressed superfluid density after time `t=200`.

https://github.com/loganbvh/py-tdgl/assets/20325010/0df2e2d4-d188-41c5-83b1-33a6e14f2db0

**Comment by loganbvh** [comment]
Added this change in https://github.com/loganbvh/py-tdgl/releases/tag/v0.8.0
